DefaultContentLanguage = "en"
author = "Ryandran Naidoo"
baseURL = ""
baseurl = "https://ryandran.com/"
copyright = "Copyright © 2008–2018, Ryandran Naidoo; all rights reserved."
disqusShortname = ""
paginate = 10
publishDir = "public"
theme = "clarity"
themesDir = "themes"
title = "Ryans Tech Blog"
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = "--"
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 2
[params]
author = "Jane Doe"
centerLogo = false
codeLineNumbers = false
codeMaxLines = 7
enableMathNotation = false
enforceLightMode = false
fallBackOgImage = "images/thumbnail.png"
figurePositionLabel = "Figure"
figurePositionShow = false
ga_analytics = "XXXXXXXXXX"
introDescription = "Technologist, perpetual student, teacher, continual incremental improvement."
languageMenuName = "🌐"
largeTwitterCard = false
logo = "logos/logo.png"
mainSections = ["post"]
mobileNavigation = "left"
numberOfTagsShown = 14
twitter = "@janedoe"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
